title: Jian's blog
description: Excited about deeping diving from high level symptoms to kernel/OS issues

theme: jekyll-theme-slate

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
